//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatisler
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tblMusteriler tblMusteriler { get; set; }
        public virtual tblUrunler tblUrunler { get; set; }
    }
}
